apiVersion: v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: my-app
    type: front-end
spec:
  template:
    metadata:
      name: nginx
      labels: front-end
    spec:
      containers:
        - name: nginx
          image: nginx

  selector:
    matchLabels:
      type: front-end
